spring:
  datasource:
    username: victory_garden
    password: victory_garden
    url: jdbc:mysql://localhost:3306/victory_garden
    
  jpa:
    hibernate: 
      ddl-auto: create
    show-sql: true  
    
  sql:
    init:
      mode: always